name: Black Code Formatting

on: [pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    name: Black
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Black
        uses: psf/black@20.8b1  # already includes args "--check --diff"